const CATALOG=[{id:'minimed-demo',title:'MiniMed: демонстрационный медицинский пакет',description:'Регистрационные сведения, медицинские термины и связи с точными источниками.',url:'packs/minimed-demo.json'}];
const state={packs:JSON.parse(localStorage.getItem('lnote.packs')||'{}'),notes:JSON.parse(localStorage.getItem('lnote.notes')||'[]')};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9\s-]/gi,' ').replace(/\s+/g,' ').trim();
function distance(a,b){a=norm(a);b=norm(b);const d=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]}
function docs(){return Object.values(state.packs).flatMap(p=>p.documents||[])} function entities(){return Object.values(state.packs).flatMap(p=>p.entities||[])}
function scoreDoc(doc,q){const nq=norm(q),terms=nq.split(' ').filter(Boolean),hay=norm([doc.title,doc.text,...(doc.aliases||[]),...(doc.tags||[])].join(' '));let score=0;for(const t of terms){if(hay.includes(t))score+=12;else{const words=hay.split(' ');const best=Math.min(...words.map(w=>distance(t,w)));if(best<=1)score+=7;else if(best===2&&t.length>5)score+=3}}return score}
function bestCorrection(q){const words=norm(q).split(' '),dictionary=[...new Set(entities().flatMap(e=>[e.name,...(e.aliases||[])]).flatMap(x=>norm(x).split(' ')))];let changed=false;const corrected=words.map(w=>{let best=w,bd=3;for(const c of dictionary){const d=distance(w,c);if(d<bd){best=c;bd=d}}if(best!==w&&w.length>4)changed=true;return best});return changed?corrected.join(' '):null}
function search(query){const hits=docs().map(d=>({...d,_score:scoreDoc(d,query)})).filter(d=>d._score>0).sort((a,b)=>b._score-a._score);renderResults(hits,query);const fix=bestCorrection(query);$('#suggestion').innerHTML=fix?`Возможно, вы искали: <button data-query="${esc(fix)}">${esc(fix)}</button>`:'';$('#suggestion button')?.addEventListener('click',e=>{$('#query').value=e.currentTarget.dataset.query;runSearch()})}
function renderResults(hits,q){$('#answer').innerHTML=hits.length?`<div class="answer"><strong>Сводка по найденным данным</strong><p>Найдено ${hits.length} связанных фрагментов. Верхний результат: «${esc(hits[0].title)}». Ответ сформирован детерминированно; откройте источник для проверки.</p></div>`:'<div class="answer">В установленных пакетах подходящих данных нет.</div>';$('#results').innerHTML=hits.map(d=>`<article class="card"><div class="source">${esc(d.source.label)} · ${esc(d.source.date||'без даты')}</div><h3>${esc(d.title)}</h3><div class="chips">${(d.tags||[]).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><p class="snippet">${esc(d.text.slice(0,340))}${d.text.length>340?'…':''}</p><button class="secondary open-doc" data-id="${esc(d.id)}">Открыть источник</button></article>`).join('');document.querySelectorAll('.open-doc').forEach(b=>b.onclick=()=>openDoc(b.dataset.id))}
function openDoc(id){const d=docs().find(x=>x.id===id);if(!d)return;const related=entities().filter(e=>(e.documentIds||[]).includes(id));$('#readerContent').innerHTML=`<div class="source">${esc(d.source.label)} · ${esc(d.source.url||'локальный источник')}</div><h1>${esc(d.title)}</h1><div class="chips">${related.map(e=>`<span class="chip">${esc(e.name)}</span>`).join('')}</div><p class="snippet">${esc(d.text)}</p><h3>Provenance</h3><pre>${esc(JSON.stringify(d.source,null,2))}</pre>`;$('#reader').showModal()}
async function installPack(item){const button=document.querySelector(`[data-pack="${item.id}"]`);button.disabled=true;button.textContent='Загрузка…';try{const response=await fetch(item.url);if(!response.ok)throw new Error(response.status);const pack=await response.json();if(pack.schemaVersion!==1||!pack.id||!Array.isArray(pack.documents))throw new Error('Некорректный пакет');state.packs[pack.id]=pack;localStorage.setItem('lnote.packs',JSON.stringify(state.packs));renderPacks();search($('#query').value||'цефтриаксон')}catch(e){button.disabled=false;button.textContent='Повторить';alert(`Не удалось установить пакет: ${e.message}`)}}
function removePack(id){delete state.packs[id];localStorage.setItem('lnote.packs',JSON.stringify(state.packs));renderPacks();renderResults([],'')}
function renderPacks(){$('#packList').innerHTML=CATALOG.map(p=>{const installed=Boolean(state.packs[p.id]);return `<article class="card pack"><div><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><span class="status">${installed?'Установлен и доступен офлайн':'Не установлен'}</span></div><button ${installed?'class="secondary"':''} data-pack="${p.id}">${installed?'Удалить':'Скачать'}</button></article>`}).join('');CATALOG.forEach(p=>{const b=document.querySelector(`[data-pack="${p.id}"]`);b.onclick=()=>state.packs[p.id]?removePack(p.id):installPack(p)})}
function renderNotes(){$('#noteList').innerHTML=state.notes.map((n,i)=>`<article class="card"><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><div class="note-links">${(n.links||[]).map(esc).join(' · ')}</div><button class="secondary delete-note" data-i="${i}">Удалить</button></article>`).join('');document.querySelectorAll('.delete-note').forEach(b=>b.onclick=()=>{state.notes.splice(Number(b.dataset.i),1);localStorage.setItem('lnote.notes',JSON.stringify(state.notes));renderNotes()})}
function runSearch(){const q=$('#query').value.trim();if(q)search(q)}
$('#searchButton').onclick=runSearch;$('#query').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});$('#closeReader').onclick=()=>$('#reader').close();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.tab}`).classList.add('active')});$('#noteForm').onsubmit=e=>{e.preventDefault();state.notes.unshift({title:$('#noteTitle').value,text:$('#noteText').value,links:$('#noteLinks').value.split(',').map(x=>x.trim()).filter(Boolean),createdAt:new Date().toISOString()});localStorage.setItem('lnote.notes',JSON.stringify(state.notes));e.target.reset();renderNotes()};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installApp').hidden=false});$('#installApp').onclick=async()=>{await deferred?.prompt();deferred=null;$('#installApp').hidden=true};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');renderPacks();renderNotes();if(!Object.keys(state.packs).length)installPack(CATALOG[0]);else search('цефтриаксон');
